name: Web Siteyi Kontrol Et

on:
  schedule:
    - cron: "*/30 * * * *"  # Her 30 dakikada bir çalışır
  workflow_dispatch:
permissions:
  contents: write 
jobs:
  check-site:
    runs-on: ubuntu-latest

    steps:
      - name: Reposu klonla
        uses: actions/checkout@v4

      - name: Python ortamını kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Gereken paketleri kur
        run: pip install python-telegram-bot==13.15 requests

      - name: Siteyi kontrol et
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python check_site.py

      - name: Git yapılandır
        run: |
          git config user.name "santral06"
          git config user.email "metemet06@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/santral06/website-monitor.git

      - name: Değişiklik varsa state branch'ine pushla
        run: |
          git fetch origin
          git checkout -B state origin/state || git checkout -b state
          git add site_hash.txt
          git commit -m "🔄 Hash güncellendi (değişiklik algılandı)" || echo "Commit yok"
          git push origin state
