name: Website Monitor

on:
  schedule:
    - cron: '*/15 * * * *'  # Her 15 dakikada bir çalışır
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (main branch)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # tüm branch'lere erişmek için

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests python-telegram-bot==13.15

      - name: Run monitor script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python check_site.py

      - name: Checkout state branch
        run: |
          git fetch origin state || echo "state branch'i yok, yeni oluşturulacak"
          git checkout -B state origin/state || git checkout -b state

      - name: Copy latest hash file from run
        run: |
          # Eğer monitor.py dosyası yeni site_hash.txt dosyası oluşturduysa onu al
          if [ -f site_hash.txt ]; then
            echo "Yeni hash bulundu. Commit için hazırlanıyor."
          else
            echo "site_hash.txt bulunamadı. Muhtemelen değişiklik yoktu."
            exit 0
          fi
          
      - name: Kopyalanan hash dosyasını al
        run: |
          if [ -f temp/site_hash.txt ]; then
            cp temp/site_hash.txt site_hash.txt
          else
            echo "Geçici hash dosyası bulunamadı. Çıkılıyor."
            exit 0
          fi

      - name: Commit and push to state branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add site_hash.txt
          git commit -m "🔄 Hash güncellendi (değişiklik algılandı)" || echo "Commit yok"
          git pull origin state --rebase || echo "Rebase gerekmedi"
          git push origin state || echo "Push başarısız olabilir (değişiklik yoksa normaldir)"
