name: Check drmustafametin.com for Changes

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main (current) branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch and checkout state branch hash file
        run: |
          git fetch origin state
          git checkout origin/state -- site_hash.txt

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run site check
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python check_site.py

      - name: Commit updated hash (if needed)
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git fetch origin state
          git switch state
          git checkout main -- check_site.py
          git add site_hash.txt
          git commit -m "Update site hash" || echo "No changes"
          git push origin state
