name: Website Kontrol ve Telegram Bildirimi

on:
  schedule:
    - cron: '*/5 * * * *' # Her 5 dakikada bir çalıştır

jobs:
  check_website:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Kontrol Et
        uses: actions/checkout@v4

      - name: Python'ı Ayarla
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Gerekli Kütüphaneleri Yükle
        run: pip install -r requirements.txt

      - name: Ortam Değişkenlerini Ayarla
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Website'i Kontrol Et ve Telegram Mesajı Gönder
        run: python check_site.py # Python scriptinizin adını buraya yazın
