name: Web Sitesi Takibi

on:
  schedule:
    - cron: "*/5 * * * *"  # Her 5 dakikada bir çalışır
  workflow_dispatch:

jobs:
  check_website:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu çek (kendi PAT ile)
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Gereksinimleri yükle
        run: pip install requests python-telegram-bot

      - name: Siteyi kontrol et
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python check_site.py

      - name: Pull with rebase and resolve conflicts automatically
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
        
          git fetch origin state || git checkout -b state
          git checkout state || git checkout -b state origin/state
      
          git pull origin state --rebase || git rebase --skip || echo "pull failed"
        
          echo "$NEW_HASH" > site_hash.txt
        
          git add site_hash.txt
          git commit -m "🔄 Hash güncellendi (değişiklik algılandı)" || echo "No changes to commit"
          git push origin state || echo "Push failed"
