name: Website Monitor
on:
  schedule:
    - cron: '*/5 * * * *'  # 5 dakikada bir (UTC)
  workflow_dispatch:  # Manuel tetikleme

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Timeout süresi
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
        - name: Run monitor with memory tracking
  env:
    PYTHONTRACEMALLOC: 2  # Enables memory tracing
    TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
    CHAT_ID: ${{ secrets.CHAT_ID }}
  run: |
    python -X tracemalloc=5 checkweb.py.py 2>&1 | tee -a logs.txt
        
