name: Website Monitor
on:
  schedule:
    - cron: '*/5 * * * *'  # 5 dakikada bir (UTC zaman dilimi)
  workflow_dispatch:  # Manuel tetikleme seçeneği

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python checkweb.py
